### ISSUE TITLE
Can't upgrade to 3.0.5821

### ISSUE THREAD

**Issue by anderbytes** [OpenMediaVault-Plugin-Developers/openmediavault-emby#3]
For some reason, my GUI shows me that version 3.0.5821 is already in release channel to upgrade. But it doesn't give me any way to run the upgrade, and it doesn't do it manually, either.

Is that normal?
Do you (DEV) has to manually do something after every update?

Thanks

**Comment by tekkbebe** [comment]
Handled on forum.
