### ISSUE TITLE
openmediavault-emby package is not installable because of broken dep openmediavault (= 3.0.13)

### ISSUE THREAD

**Issue by lissyx** [OpenMediaVault-Plugin-Developers/openmediavault-emby#5]
Hello,

STR:
1. Install OMV
2. Perform upgrades
3. Install/enable extra repos (Mono stable repo)
4. Try to install openmediavault-emby

Expected:
 Install succeeds

Actual:
 Install fails because the openmediavault version available is now 3.0.25, which conflicts with the current dependency against 3.0.13

This is happening on OpenMediaVault 3 serie, so maybe since it's still exposed as beta it's not such a big deal?

**Comment by lissyx** [comment]
@tekkbebe thanks for your work, do you know if there is currently some on-going fix for that issue? As much as I could search for it I found nothing :/

**Comment by ryecoaaron** [comment]
The plugin needs to be ported to 3.0.25.  Nothing you can do to fix it until then.
